### ISSUE TITLE
Problems with dependencies (jinja2?)

### ISSUE THREAD

**Issue by penserbjorne** [Te-k/sdanalyzer#4]
Hi, @Te-k!

I'm triying to use the tool and I'm getting these errors.

Creating a phone.
```
$ sdanalyzer phones --create "P test"
Traceback (most recent call last):
  File "/home/penserbjorne/.local/bin/sdanalyzer", line 5, in <module>
    from sdanalyzer.main import main
  File "/home/penserbjorne/.local/lib/python3.10/site-packages/sdanalyzer/main.py", line 15, in <module>
    from .app import app, Phone, Apk
  File "/home/penserbjorne/.local/lib/python3.10/site-packages/sdanalyzer/app.py", line 4, in <module>
    from flask import Flask, render_template, request, redirect, send_file, jsonify, flash
  File "/home/penserbjorne/.local/lib/python3.10/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/home/penserbjorne/.local/lib/python3.10/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/home/penserbjorne/.local/lib/python3.10/site-packages/itsdangerous/__init__.py)
```

Importing apps. I guess this could be expected as the previous step failed. The folder `.` actually contains a backup of apks extracted with `androidqf`.
```
$ sdanalyzer import --phone 1 .
Traceback (most recent call last):
  File "/home/penserbjorne/.local/bin/sdanalyzer", line 5, in <module>
    from sdanalyzer.main import main
  File "/home/penserbjorne/.local/lib/python3.10/site-packages/sdanalyzer/main.py", line 15, in <module>
    from .app import app, Phone, Apk
  File "/home/penserbjorne/.local/lib/python3.10/site-packages/sdanalyzer/app.py", line 4, in <module>
    from flask import Flask, render_template, request, redirect, send_file, jsonify, flash
  File "/home/penserbjorne/.local/lib/python3.10/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/home/penserbjorne/.local/lib/python3.10/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json

```

Serving the app.
```
$ sdanalyzer serve
Traceback (most recent call last):
  File "/home/penserbjorne/.local/bin/sdanalyzer", line 5, in <module>
    from sdanalyzer.main import main
  File "/home/penserbjorne/.local/lib/python3.10/site-packages/sdanalyzer/main.py", line 15, in <module>
    from .app import app, Phone, Apk
  File "/home/penserbjorne/.local/lib/python3.10/site-packages/sdanalyzer/app.py", line 4, in <module>
    from flask import Flask, render_template, request, redirect, send_file, jsonify, flash
  File "/home/penserbjorne/.local/lib/python3.10/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/home/penserbjorne/.local/lib/python3.10/site-packages/jinja2/__init__.py)
```

FYI
Distro: `Pop!_OS`
Python version: `3.10`
The tool was install with pip `pip install sdanalyzer`

Thanks!

**Comment by AntoninHuaut** [comment]
I [forked](https://github.com/AntoninHuaut/sdanalyzer) and updated the dependencies (Flask): this solves the error
But all apk (extracted from my phone with [androidqf](https://github.com/botherder/androidqf)) return
```
Parsing Error from androguard, this app will be ignored
Invalid format string
```

Edit: It was a Windows problem (https://github.com/Te-k/sdanalyzer/pull/6), so it should work

**Comment by Te-k** [comment]
Thanks @AntoninHuaut and sorry for the delay. @penserbjorne can you check if this works on your side?

**Comment by penserbjorne** [comment]
Hi @Te-k!

I can confirm that the tool is now working on my local (cloned from the repo), and everything seems to be working fine. 

Thanks for the update. :smile:
